name: Secure CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    # 🔍 SonarCloud (Code Scan)
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      with:
        args: >
          -Dsonar.projectKey=Nitin8604_secure-ci-cd
          -Dsonar.organization=nitin8604
          -Dsonar.sources=.
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # 🔐 Install Snyk
    - name: Install Snyk
      run: npm install -g snyk

    # 🔐 Authenticate Snyk
    - name: Snyk Auth
      run: snyk auth "${{ secrets.SNYK_TOKEN }}"

    # 🔐 Dependency Scan
    - name: Snyk Scan
      run: snyk test || true

    # 🐳 Build Docker Image
    - name: Build Docker Image
      run: docker build -t secure-app .

    # 🔐 Container Scan (Trivy)
    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'secure-app'